name: continuous-integration

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull_request:
        branches-ignores: [ga-ignore-*]

jobs:

    coding-style:

    compile:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout GH repo
            uses: actions/checkout@v4
          
          - name: Compile repository
            run: make

          - name: Check binary presence
            run: |
              if [ ! -f ./swapupcase ]; then
                  echo "::error file=swapupcase,titl=Binary
                  Error::Binary not found"
                  exit 1
                fi
                exit 0